### ISSUE TITLE
Refactor the library such that it doesn't need to look at environment variables

### ISSUE THREAD

**Issue by ehashman** [rackerlabs/cloudpassage-lib#12]
Here's an example of an error message that doesn't say very much:

```
=> (scans/fim-report! "$ID" "$KEY")
16-03-11 20:25:17 MJV0HLDKQ4 INFO [cloudpassage-lib.core] - fetching new auth token for $ID
Mar 11, 2016 2:25:17 PM clojure.tools.logging$eval420$fn__424 invoke
SEVERE: error in stream handler
java.lang.NullPointerException
    at java.util.Arrays.copyOfRange(Arrays.java:3521)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at fernet.core$split_key.invokeStatic(core.clj:29)
    at fernet.core$split_key.invoke(core.clj:28)
    ...
```

Yay NPE!

The actual problem here was that the fernet key/redis environment variables weren't set properly in profiles.clj. It would be great to do some checking for that and provide a more user-friendly error message.

**Comment by derwolfe** [comment]
Thanks for reporting this issue. :-)

I'm a bit unsure that this is a library level concern; in fact, I'm inclined to say that the library shouldn't be consuming environment variables at all. Consumers of the library should be passing parameters to functions.

The reason the current code is relying on environment variables is because I extracted the logic directly from an application without alteration.

Currently, the library relies on the following variables to function
1. Redis-url (basically a db connection string)
2. Redis-timeout
3. Fernet-key

`scans/get-page!` does indeed rely on `fernet-key` existing in the environment; in my opinion, this should removed in favor of passing a parameter into the function. The reason I prefer this approach is because it pushes the input validation onto the application. Any consuming application will have a set of environment variables that should be set in order to function; further, this allows the application to determine what sort of remediation should occur in the event of a bad env-var having been used.

Regarding the redis-url and timeout keys; I'd also prefer that these not be sourced by the environment directly (that is, `core/redis-connection` should take some parameters). Again, this makes it possible for consuming applications to pass in the connection information however they see fit. Further, it reduces the dependency of the library on global state needing to exist. This will likely require rewriting the `wcar` macro so that it can take some connection information as parameters.

**Comment by ehashman** [comment]
Chris, I definitely agree. I don't think a library should be consuming environment variables; that should be the app's problem. However, given that the library currently *does* consume them, this issue is still applicable.

As such, in order to resolve it, let's refactor this code to consume passed configuration variables and let the end application deal with how those variables find their way to the consumers.
